// <auto-generated />
using System;
using HOT3.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HOT3.Migrations
{
    [DbContext(typeof(StoreContext))]
    partial class StoreContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HOT3.Models.Purchase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("TableId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("TableId");

                    b.ToTable("Purchases");
                });

            modelBuilder.Entity("HOT3.Models.Table", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageFileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Tables");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Homary",
                            Description = "This accent desk is made from hardwood and wrought metal, with one floating drawer.",
                            ImageFileName = "desk1.jpg",
                            Name = "Homary Cabstract Executive Office Desk",
                            Price = 879.99m
                        },
                        new
                        {
                            Id = 2,
                            Brand = "BYBLIGHT",
                            Description = "Rectangular White wood 2-drawer computer desk",
                            ImageFileName = "desk2.jpg",
                            Name = "BYBLIGHT Capen",
                            Price = 214.24m
                        },
                        new
                        {
                            Id = 3,
                            Brand = "Homary",
                            Description = "Rising and Lowering wooden desk",
                            ImageFileName = "desk3.jpg",
                            Name = "Modern Standing/sitting desk",
                            Price = 319.49m
                        },
                        new
                        {
                            Id = 4,
                            Brand = "BYBLIGHT",
                            Description = "L-Shaped Brown Engineered wood 4-drawer computer desk",
                            ImageFileName = "desk4.jpg",
                            Name = "BYBLIGHT Lanita",
                            Price = 559.99m
                        },
                        new
                        {
                            Id = 5,
                            Brand = "BYBLIGHT",
                            Description = "Space-Saving corner workstation with storage shelves",
                            ImageFileName = "desk5.jpg",
                            Name = "SILKYDRY Small Corner Desk",
                            Price = 119.99m
                        });
                });

            modelBuilder.Entity("HOT3.Models.Purchase", b =>
                {
                    b.HasOne("HOT3.Models.Table", "Table")
                        .WithMany()
                        .HasForeignKey("TableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Table");
                });
#pragma warning restore 612, 618
        }
    }
}
