// <auto-generated />
using System;
using FandomFinds.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FandomFinds.Migrations
{
    [DbContext(typeof(ShopContext))]
    [Migration("20251208001109_IdentityFix")]
    partial class IdentityFix
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FandomFinds.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("FandomFinds.Models.Brand", b =>
                {
                    b.Property<int>("BrandId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BrandId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BrandId");

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            BrandId = 1,
                            Name = "Nintendo"
                        },
                        new
                        {
                            BrandId = 2,
                            Name = "S.H Figuarts"
                        },
                        new
                        {
                            BrandId = 3,
                            Name = "Funko"
                        },
                        new
                        {
                            BrandId = 4,
                            Name = "Hasbro"
                        },
                        new
                        {
                            BrandId = 5,
                            Name = "Tomy"
                        },
                        new
                        {
                            BrandId = 6,
                            Name = "Jakks"
                        });
                });

            modelBuilder.Entity("FandomFinds.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OrderName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("OrderId");

                    b.HasIndex("ApplicationUserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("FandomFinds.Models.OrderItem", b =>
                {
                    b.Property<int>("OrderItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderItemId"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("OrderItemId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("FandomFinds.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.HasIndex("BrandId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            BrandId = 1,
                            Description = "Booster pack with 10 cards and a code card for online game. Each pack is random.",
                            ImagePath = "/images/destined-rival.jpg",
                            ImageUrl = "/images/destined-rival.jpg",
                            Name = "Destined Rival TCG Pokemon",
                            Price = 5.99m,
                            Stock = 0
                        },
                        new
                        {
                            ProductId = 2,
                            BrandId = 2,
                            Description = "High end action figure. Highly articulated.",
                            ImagePath = "/images/spiderman.jpg",
                            ImageUrl = "/images/spiderman.jpg",
                            Name = "S.H Figuarts Spider-Man",
                            Price = 65.99m,
                            Stock = 0
                        },
                        new
                        {
                            ProductId = 3,
                            BrandId = 2,
                            Description = "High end action figure. Highly articulated.",
                            ImagePath = "/images/broly.jpg",
                            ImageUrl = "/images/broly.jpg",
                            Name = "S.H Figuarts Broly",
                            Price = 89.99m,
                            Stock = 0
                        },
                        new
                        {
                            ProductId = 4,
                            BrandId = 3,
                            Description = "Vinyl Collectable figure 6 inches in height",
                            ImagePath = "/images/metal-sonic-funko.jpg",
                            ImageUrl = "/images/metal-sonic-funko.jpg",
                            Name = "Metal Sonic Funko Pop",
                            Price = 12.99m,
                            Stock = 0
                        },
                        new
                        {
                            ProductId = 5,
                            BrandId = 5,
                            Description = "Collectable. Rare find",
                            ImagePath = "/images/blaziken.jpg",
                            ImageUrl = "/images/blaziken.jpg",
                            Name = "Pokemon figure- Mega Blaziken",
                            Price = 109.99m,
                            Stock = 0
                        },
                        new
                        {
                            ProductId = 6,
                            BrandId = 6,
                            Description = "5in Mario figure in cat suit. Includes a question box. Exclusive movie merch",
                            ImagePath = "/images/cat-mario.jpg",
                            ImageUrl = "/images/cat-mario.jpg",
                            Name = "Cat Mario",
                            Price = 14.99m,
                            Stock = 0
                        },
                        new
                        {
                            ProductId = 7,
                            BrandId = 2,
                            Description = "High end action figure. Highly articulated. 2 pack. Reenact scenes from the manga with the high poseable figures",
                            ImagePath = "/images/chainsawman.jpg",
                            ImageUrl = "/images/chainsawman.jpg",
                            Name = "S.h. Figuarts Denji chainsaw man figure. Double pack",
                            Price = 149.99m,
                            Stock = 0
                        },
                        new
                        {
                            ProductId = 8,
                            BrandId = 2,
                            Description = "High end action figure. Highly articulated. Includes lightsabers.",
                            ImagePath = "/images/grevious.jpg",
                            ImageUrl = "/images/grevious.jpg",
                            Name = "StarWars General Grevious figure",
                            Price = 89.99m,
                            Stock = 0
                        },
                        new
                        {
                            ProductId = 9,
                            BrandId = 2,
                            Description = "High end action figure. Highly articulated. Includes sword and cape. 12in figure.",
                            ImagePath = "/images/king-cold.jpg",
                            ImageUrl = "/images/king-cold.jpg",
                            Name = "King Cold-Dragonball figure",
                            Price = 109.99m,
                            Stock = 0
                        },
                        new
                        {
                            ProductId = 10,
                            BrandId = 6,
                            Description = "4 characters all included in this special pack. Articulated. Detailed designs. Inspired by the movie! Perfect set for collectors",
                            ImagePath = "/images/mario-set.jpg",
                            ImageUrl = "/images/mario-set.jpg",
                            Name = "Mario Set 4 pack",
                            Price = 49.99m,
                            Stock = 0
                        },
                        new
                        {
                            ProductId = 11,
                            BrandId = 2,
                            Description = "Very rare mario figure. Brand new. Sealed.",
                            ImagePath = "/images/mario-sh.jpg",
                            ImageUrl = "/images/mario-sh.jpg",
                            Name = "Mario S.H. Figuarts",
                            Price = 149.99m,
                            Stock = 0
                        },
                        new
                        {
                            ProductId = 12,
                            BrandId = 6,
                            Description = "Hard to find. Articulated. Very detailed ",
                            ImagePath = "/images/metal-sonic.jpg",
                            ImageUrl = "/images/metal-sonic.jpg",
                            Name = "Metal Sonic figure",
                            Price = 69.99m,
                            Stock = 0
                        },
                        new
                        {
                            ProductId = 13,
                            BrandId = 2,
                            Description = "High end action figure. Highly articulated. Includes many accessories. Realistic.",
                            ImagePath = "/images/miles.jpg",
                            ImageUrl = "/images/miles.jpg",
                            Name = "S.H Figuarts Miles Morales figure",
                            Price = 89.99m,
                            Stock = 0
                        },
                        new
                        {
                            ProductId = 14,
                            BrandId = 6,
                            Description = "Hard to find. Articulated. Very detailed ",
                            ImagePath = "/images/metal-sonic.jpg",
                            ImageUrl = "/images/metal-sonic.jpg",
                            Name = "Metal Sonic figure",
                            Price = 69.99m,
                            Stock = 0
                        },
                        new
                        {
                            ProductId = 15,
                            BrandId = 4,
                            Description = "Reenact classic scenes from highly popular show Stranger Things. Includes Demigorgan, Dustin and Will. ",
                            ImagePath = "/images/stranger-set.jpg",
                            ImageUrl = "/images/stranger-set.jpg",
                            Name = "Stranger Things Character set",
                            Price = 29.99m,
                            Stock = 0
                        },
                        new
                        {
                            ProductId = 16,
                            BrandId = 2,
                            Description = "Hard to find. Articulated. Very detailed ",
                            ImagePath = "/images/scarletspider.jpg",
                            ImageUrl = "/images/scarletspider.jpg",
                            Name = "Scarlet Spiderman",
                            Price = 99.99m,
                            Stock = 0
                        },
                        new
                        {
                            ProductId = 17,
                            BrandId = 4,
                            Description = "Hard to find. From season one of Strangers Things. Eleven in dress with shaved head.",
                            ImagePath = "/images/stranger-11.jpg",
                            ImageUrl = "/images/stranger-11.jpg",
                            Name = "Eleven Stranger Things figure",
                            Price = 59.99m,
                            Stock = 0
                        },
                        new
                        {
                            ProductId = 18,
                            BrandId = 2,
                            Description = "Articulated. Very detailed. Accessories included. Collect them all!",
                            ImagePath = "/images/power.jpg",
                            ImageUrl = "/images/power.jpg",
                            Name = "Chainsaw Man Power Figure",
                            Price = 79.99m,
                            Stock = 0
                        },
                        new
                        {
                            ProductId = 19,
                            BrandId = 4,
                            Description = "Collectable. In original packaging. Perfect condition. Perfect for the collector in you life.",
                            ImagePath = "/images/optimus-prime.jpg",
                            ImageUrl = "/images/optimus-prime.jpg",
                            Name = "Transformers Optimus Prime figure",
                            Price = 29.99m,
                            Stock = 0
                        });
                });

            modelBuilder.Entity("FandomFinds.Models.ProductReview", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("ReviewText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReviewerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ProductReviews");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ProductId = 1,
                            Rating = 5,
                            ReviewText = "Great pack, got a super rare card too! It's my form of gambling. Lol.",
                            ReviewerName = "Thomas"
                        },
                        new
                        {
                            Id = 2,
                            ProductId = 2,
                            Rating = 4,
                            ReviewText = "Amazing figure quality! It articulates so well.",
                            ReviewerName = "Peter"
                        },
                        new
                        {
                            Id = 3,
                            ProductId = 4,
                            Rating = 5,
                            ReviewText = "Cute Funko Pop. I have a huge collection and I'm so excited to add this to the collection!",
                            ReviewerName = "Amy"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("FandomFinds.Models.Order", b =>
                {
                    b.HasOne("FandomFinds.Models.ApplicationUser", "User")
                        .WithMany("Orders")
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FandomFinds.Models.OrderItem", b =>
                {
                    b.HasOne("FandomFinds.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FandomFinds.Models.Product", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("FandomFinds.Models.Product", b =>
                {
                    b.HasOne("FandomFinds.Models.Brand", "Brand")
                        .WithMany()
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("FandomFinds.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("FandomFinds.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FandomFinds.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("FandomFinds.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FandomFinds.Models.ApplicationUser", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("FandomFinds.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("FandomFinds.Models.Product", b =>
                {
                    b.Navigation("OrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
