// <auto-generated />
using FandomFinds.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FandomFinds.Migrations
{
    [DbContext(typeof(ShopContext))]
    [Migration("20251012183039_seedData")]
    partial class seedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FandomFinds.Models.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Nintendo"
                        },
                        new
                        {
                            Id = 2,
                            Name = "S.H Figuarts"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Funko"
                        });
                });

            modelBuilder.Entity("FandomFinds.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Nintendo",
                            Description = "Booster pack with 10 cards and a code card for online game. Each pack is random.",
                            Name = "Destined Rival TCG Pokemon",
                            Price = 5.99m
                        },
                        new
                        {
                            Id = 2,
                            Brand = "sh figuarts",
                            Description = "High end action figure. Highly articulated.",
                            Name = "S.H Figuarts Spider-Man",
                            Price = 65.99m
                        },
                        new
                        {
                            Id = 3,
                            Brand = "sh figuarts",
                            Description = "High end action figure. Highly articulated.",
                            Name = "S.H Figuarts Broly",
                            Price = 89.99m
                        },
                        new
                        {
                            Id = 4,
                            Brand = "Funko",
                            Description = "Vinyl Collectable figure 6 inches in height",
                            Name = "Metal Sonic Funko Pop",
                            Price = 12.99m
                        });
                });

            modelBuilder.Entity("FandomFinds.Models.ProductReview", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("ReviewText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReviewerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ProductReviews");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ProductId = 1,
                            Rating = 5,
                            ReviewText = "Great pack, got a super rare card too! It's my form of gambling. Lol.",
                            ReviewerName = "Thomas"
                        },
                        new
                        {
                            Id = 2,
                            ProductId = 2,
                            Rating = 4,
                            ReviewText = "Amazing figure quality! It articulates so well.",
                            ReviewerName = "Peter"
                        },
                        new
                        {
                            Id = 3,
                            ProductId = 4,
                            Rating = 5,
                            ReviewText = "Cute Funko Pop. I have a huge collection and I'm so excited to add this to the collection!",
                            ReviewerName = "Amy"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
