// <auto-generated />
using HOT2.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HOT2.Migrations
{
    [DbContext(typeof(ProductContext))]
    [Migration("20250921232901_first")]
    partial class first
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HOT2.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Components"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Accessories"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Tools"
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryName = "Home Improvement"
                        },
                        new
                        {
                            CategoryId = 5,
                            CategoryName = "Lighting"
                        });
                });

            modelBuilder.Entity("HOT2.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<int?>("CategoryID")
                        .HasColumnType("int");

                    b.Property<string>("ProductDescLong")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductDescShort")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ProductPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductQty")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryID")
                        .IsUnique()
                        .HasFilter("[CategoryID] IS NOT NULL");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryID = 1,
                            ProductDescLong = "",
                            ProductDescShort = "",
                            ProductImage = "",
                            ProductName = "AeroFlo ATB Wheels",
                            ProductPrice = 189.00m,
                            ProductQty = 40
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryID = 2,
                            ProductDescLong = "",
                            ProductDescShort = "",
                            ProductImage = "",
                            ProductName = "Clear Shade 85-T Glasses",
                            ProductPrice = 45.00m,
                            ProductQty = 14
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryID = 3,
                            ProductDescLong = "",
                            ProductDescShort = "",
                            ProductImage = "",
                            ProductName = "Cosmic Elite Road Warrior Wheels",
                            ProductPrice = 160.00m,
                            ProductQty = 22
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryID = 4,
                            ProductDescLong = "",
                            ProductDescShort = "",
                            ProductImage = "",
                            ProductName = "Cycle-Doc Pro Repair Stand",
                            ProductPrice = 166.00m,
                            ProductQty = 12
                        },
                        new
                        {
                            ProductId = 5,
                            CategoryID = 5,
                            ProductDescLong = "",
                            ProductDescShort = "",
                            ProductImage = "",
                            ProductName = "Dog Ear Aero-Flow Floor Pump",
                            ProductPrice = 55.00m,
                            ProductQty = 22
                        });
                });

            modelBuilder.Entity("HOT2.Models.Product", b =>
                {
                    b.HasOne("HOT2.Models.Category", "Category")
                        .WithOne("Product")
                        .HasForeignKey("HOT2.Models.Product", "CategoryID");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("HOT2.Models.Category", b =>
                {
                    b.Navigation("Product");
                });
#pragma warning restore 612, 618
        }
    }
}
